### ISSUE TITLE
新需求

### ISSUE THREAD

**Issue by CrystalGirls** [caoxinyu/RedisClient#100]
由于应用和Redis在同一台服务器上，因此为了Redis的安全，端口没有开放到外网，程序部署在服务器上可以正常连接，但是在试运行的时候，需要查看Redis上的数据，现在只能通过ssh登陆上去之后使用命令操作，不知道RedisClient何时支持通过SSH跳转隧道连接到Redis。

**Comment by caoxinyu** [comment]
有一个简单的解决办法，在你的机器上装一个ssh客户端，然后执行ssh命令建立隧道，就可以了。类似这样：

_ssh -L 6379:localhost:6379 -N root@47.92.235.38_

6379是远端redis server的端口，root@47.92.235.38是远端机器的ip和用户。
