### ISSUE TITLE
当连接到一个带密码的redis的时候，执行命令总是报错

### ISSUE THREAD

**Issue by 700neo007** [caoxinyu/RedisClient#15]
当连接到一个带密码的redis的时候，执行命令总是报错
报错信息如下：
命令: keys hello:world
时间: 2015-04-28 20:50:53:661
时长(ms): 1
结果:
ERR operation not permitted

**Comment by flyercao** [comment]
应该是你没有登录 试试先执行  auth myPassword
其实应该可以做到自动登录的
