### ISSUE TITLE
控制台连接断开后，没有重连机制

### ISSUE THREAD

**Issue by mu936k** [caoxinyu/RedisClient#17]
控制台连接断开后，没有重连机制，只能把所有文本复制，关闭后重连，再粘贴进去。
有时网络不稳定，每次都要这样，太麻烦，希望能改进。

**Comment by caoxinyu** [comment]
执行命令时，如果发现连接失效，重新连接后，再执行命令。

**Comment by Gradven** [comment]
支持到redis3.0版本了没？

**Comment by caoxinyu** [comment]
这个问题和版本没关系。

**Comment by Gradven** [comment]
我用你的2.0版本去连接redis 2.9.54版本时，提示版本太低了，是什么原因呢？

**Comment by caoxinyu** [comment]
没有测试过redis 2.9.54，简单用过redis 3.0，没碰到什么问题，可能有些小地方和低版本有些不一样，所以判断为版本太低了。

**Comment by Gradven** [comment]
多谢解答！

**Comment by tisswb** [comment]
redis3.2.3提示redis版本太低

**Comment by caoxinyu** [comment]
没有测试过redis3.2.3，可能3.2.3的接口有些变化，所以会判断版本过低
