### ISSUE TITLE
Redis data explorer 的table空白处刷新，会刷新整个Redis servers目录

### ISSUE THREAD

**Issue by flyercao** [caoxinyu/RedisClient#18]
建议：Redis data explorer 的table空白处和左边Redis servers空白处的刷新，应该只刷新选中的节点，这样可以保证空白处刷新不会改变Redis data explorer的显示内容

**Comment by caoxinyu** [comment]
选择菜单中的刷新或者是工具栏中的刷新按钮是实现你所说的要求。
