### ISSUE TITLE
双击查看key 为空的数据，之后就不能再查看其他数据了，提示：Please input key name!

### ISSUE THREAD

**Issue by flyercao** [caoxinyu/RedisClient#19]
![image](https://cloud.githubusercontent.com/assets/7811182/7853985/6d9219d6-0547-11e5-89da-2840b602b63a.png)
 
先双击查看key 为空的数据，
之后就不能再查看其他数据了，提示：Please input key name!
调试发现 
NewDataContent.java  line:163 抛出异常
分析发现 line:162的判断是多余的

**Comment by caoxinyu** [comment]
为什么会有key为空的数据？

**Comment by flyercao** [comment]
redis 支持key为空啊

**Comment by flyercao** [comment]
虽然实际生产环境很少出现，但是毕竟Redis并不禁止

**Comment by caoxinyu** [comment]
删除了key是否为空的判断
