### ISSUE TITLE
连接到redis之后，一直是read timeout

### ISSUE THREAD

**Issue by linsongze** [caoxinyu/RedisClient#20]
![qq 20150601135706](https://cloud.githubusercontent.com/assets/2689298/7907008/596807fa-0866-11e5-9862-18e47847fc90.gif)
![qq 20150601135640](https://cloud.githubusercontent.com/assets/2689298/7907010/5dda8510-0866-11e5-9df2-c3e319a4f289.gif)
如图，我在连接到redis之后，一直是socket read time out。

**Comment by caoxinyu** [comment]
请在菜单 工具-选项-连接超时 中设置超时参数
