### ISSUE TITLE
连上redis之后，无论点击哪个都报socket time out

### ISSUE THREAD

**Issue by linsongze** [caoxinyu/RedisClient#21]
![qq 20150601135706](https://cloud.githubusercontent.com/assets/2689298/7975540/8d63c9d0-0aa1-11e5-9341-3692822d12bd.gif)
![qq 20150601135640](https://cloud.githubusercontent.com/assets/2689298/7975541/916a9040-0aa1-11e5-93ff-662dd61ebbb6.gif)

**Comment by caoxinyu** [comment]
在菜单 工具-选项-连接超时 中设置超时参数，还不行么？
