### ISSUE TITLE
请教下jedis.keys()可以限制返回数量么？

### ISSUE THREAD

**Issue by Gradven** [caoxinyu/RedisClient#29]
通过其他方法限制返回数量也可以。

**Comment by caoxinyu** [comment]
jedis.keys实现的redis的keys命令，不能限制返回数量，可以考虑用scan命令

**Comment by Gradven** [comment]
do {
			ScanResult ret = jedis.scan(scanRet, scanParams);
			scanRet = ret.getStringCursor();
			retList.addAll(ret.getResult());
			
			if (retList.size() > 10)
			{
				String aa = retList.get(1).toString();
				
				System.out.println("=======aa:" + aa);
				break;
			}
						
			
		} while (!scanRet.equals("0"));

**Comment by Gradven** [comment]
找到了以上代码可用，多谢！
