### ISSUE TITLE
sockettimeout exception

### ISSUE THREAD

**Issue by lizhuangs** [caoxinyu/RedisClient#36]
双击其中某个db时报这个错误，而我用其它的redis工具都没有报这个错误。
考虑可能是网络或者数据过多导致的，建议将连接超时时间设置长一点，比如5s以上。

**Comment by caoxinyu** [comment]
可以在菜单 工具-选项-连接超时 中设置超时参数

**Comment by lizhuangs** [comment]
tks very much~~~e
