### ISSUE TITLE
导出数据到本地出错和IP地址上报

### ISSUE THREAD

**Issue by cxmxiaoke** [caoxinyu/RedisClient#39]
你可以试下，不管选择那个数据库导出都本地都报错，我的redis版本是2.4.5，还有什么你这个客户端要自动上报IP地址呢，360都拦截啦。

**Comment by caoxinyu** [comment]
能否给出更详细的错误信息，我这里导出到文件没有问题。

我这个是开源系统，你可以看看源代码，有没有要上报ip地址的。我要你的ip地址好像没啥用。

**Comment by cxmxiaoke** [comment]
![image](https://cloud.githubusercontent.com/assets/17856184/13817005/79071c9c-ebcb-11e5-9684-22ac455553c7.png)

没错误，这个就是导出时弹的对话框，我想给你错误信息都给不了，什么错误都不显示，这个RedisClient版本是1.5.0的

**Comment by caoxinyu** [comment]
1.5好像是有这个bug，你换成2.0吧
