### ISSUE TITLE
连接服务器后提示服务器版本过低不支持

### ISSUE THREAD

**Issue by liuxyc** [caoxinyu/RedisClient#43]
服务器是redis 3.2版，请问客户端支持什么版本的服务器？

**Comment by caoxinyu** [comment]
3.0版以后没有测试过。

**Comment by rayrelay** [comment]
我也遇到这个问题了，什么时间可以修复？

**Comment by caoxinyu** [comment]
底层使用的jedis还不支持redis 3.2

**Comment by rayrelay** [comment]
JedisCommand：增加这个版本判断可以解决问题
	if (version.startsWith("3.2"))
            return RedisVersion.REDIS_3_0;
	else if (version.startsWith("3.0"))
	    return RedisVersion.REDIS_3_0;

**Comment by caoxinyu** [comment]
fixed
