### ISSUE TITLE
网络不好时，会断线

### ISSUE THREAD

**Issue by kuainiao** [caoxinyu/RedisClient#44]
比RedisDesktopManager好用太多了，功能丰富实用，就是有时候连外网连不上或者掉线情况出现。

**Comment by caoxinyu** [comment]
是不是连接超时设小了。

**Comment by kuainiao** [comment]
谢谢！在选项里面把超时连接时间调长以后问题改善了，我刚才测试调很小时候这个问题就重现了。谢谢！
