### ISSUE TITLE
Error: version is too low

### ISSUE THREAD

**Issue by win32nipuh** [caoxinyu/RedisClient#47]
I installed the latest Redis for Windows 3.2.
Run Client, added local server and double-click or Refresh the server in tree.
"Error: The version of redis server is too low to support this function"

The Client does now show the tree, console works.

**Comment by caoxinyu** [comment]
Which versioon your redis server is?  Many people found redisclient can not support redis latest version, because redis interface changed.

**Comment by win32nipuh** [comment]
It is 
[ Redis on Windows 3.2.100 ] Release date: Jul 01 2016

https://github.com/MSOpenTech/redis/blob/win-3.2.100/Redis%20on%20Windows%20Release%20Notes.md

https://github.com/MSOpenTech/redis/releases/download/win-3.2.100/Redis-x64-3.2.100.msi

**Comment by win32nipuh** [comment]
Hi, do we have any hope to fix this bug?
thnx.

**Comment by caoxinyu** [comment]
yes, I have find the problem

**Comment by win32nipuh** [comment]
Great! waiting on solution ;-)

**Comment by caoxinyu** [comment]
fixed
