### ISSUE TITLE
The version of redis server is too low to support this function

### ISSUE THREAD

**Issue by asushiye** [caoxinyu/RedisClient#55]
error:
The version of redis server is too low to support this function

env:
redis server 3.2.0
redisclient-win32.x86.2.0.exe

**Comment by caoxinyu** [comment]
暂时不支持redis 3.1以上版本

**Comment by caoxinyu** [comment]
fixed

**Comment by win32nipuh** [comment]
I have installed 3.2.100 for Windows
https://github.com/MSOpenTech/redis/releases

Run the latest version of the Redis Client. It does not work:
1. The version of redis server is too low to support this function
2. Sometimes it gives: 
java.net.SocketTimeoutException: connect timed out
