### ISSUE TITLE
版本3.2.6不支持

### ISSUE THREAD

**Issue by liubiqu** [caoxinyu/RedisClient#66]
如题

**Comment by caoxinyu** [comment]
请参见问题#61 
请使用下面的版本：
[redisclient-win32.x86.2.0.exe](https://raw.githubusercontent.com/caoxinyu/RedisClient/windows/release/redisclient-win32.x86.2.0.exe)
[redisclient-win32.x86_64.2.0.jar](https://github.com/caoxinyu/RedisClient/blob/windows/release/redisclient-win32.x86_64.2.0.jar?raw=true)

**Comment by autodataming** [comment]
redisclient2.0 不支持 Redis 3.2.100； win10;

**Comment by caoxinyu** [comment]
换成项目release目录下的redisclient也不行？

**Comment by LSL1618** [comment]
RedisClient 2.0以下的老版本支持RedisServer的新版本。
