### ISSUE TITLE
客户端生成

### ISSUE THREAD

**Issue by chovy-3012** [caoxinyu/RedisClient#68]
请教下前辈，阅读前辈的redisclient源码后，了解到是用swt纯java写出来的界面，发布的客户端里面加了一个jre，直接运行了jar -jar XXX启动的。
我自己用swt写了一个项目，启动的时候写了脚本，脚本里面写 java -jar xxx，但是启动的时候会多出现一个dos的黑框。现在想知道前辈的redisclient.exe是用什么怎么封装进去命令的，谢谢了。

**Comment by caoxinyu** [comment]
不是写脚本，用jsmooth
