### ISSUE TITLE
前辈能不能把database直接写成16个，有些云redis不支持config命令，谢谢。

### ISSUE THREAD

**Issue by kuainiao** [caoxinyu/RedisClient#69]
有些云redis不支持获取这个参数，能不直接写成16个，发布一个支持16个的版本，谢谢。
public void command() {
List dbs = jedis.configGet("databases");
if(dbs.size() > 0)
dbAmount = Integer.parseInt(dbs.get(1));
else
dbAmount = 15;
}

**Comment by caoxinyu** [comment]
对不起，这段时间比较忙，请稍等一段时间

**Comment by kuainiao** [comment]
好的，谢谢大神。

**Comment by caoxinyu** [comment]
试一试这个吧，我这里没有你哪的环境，你看是否可以运行

[https://github.com/caoxinyu/RedisClient/blob/windows/release/redisclient-win32.x86_64.2.0.jar?raw=true](url)

**Comment by kuainiao** [comment]
谢谢！我是用没带jdk的版本，有exe格式的版本吗？

**Comment by caoxinyu** [comment]
[https://raw.githubusercontent.com/caoxinyu/RedisClient/windows/release/redisclient-win32.x86.2.0.exe](url)

**Comment by kuainiao** [comment]
谢谢。完美，云redis和手动搭建的都可以。
