### ISSUE TITLE
不支持windows版本的redis吗？

### ISSUE THREAD

**Issue by binarywang** [caoxinyu/RedisClient#73]
https://github.com/MicrosoftArchive/redis/releases
我装了最新的windows的redis 3.2.100版本，连接时报Redis服务器版本低

**Comment by caoxinyu** [comment]
你用的是旧版本，这个bug已经在新版本中解决了

**Comment by binarywang** [comment]
最新版本不是2.0.0 Release吗，很久没更新了吧？
https://github.com/caoxinyu/RedisClient/releases
在哪儿能得到最新的版本？

**Comment by caoxinyu** [comment]
https://raw.githubusercontent.com/caoxinyu/RedisClient/windows/release/redisclient-win32.x86.2.0.exe

**Comment by binarywang** [comment]
那这个其实跟以下页面显示的这个不是同一个文件吧？版本号还是一样的，所以我以为没有更新的
https://github.com/caoxinyu/RedisClient/releases
2.0.0 Release
@caoxinyu caoxinyu released this on 25 Sep 2014

**Comment by caoxinyu** [comment]
不是一个文件，这个文件放在项目的release目录下。

**Comment by binarywang** [comment]
那我知道了，之前一直习惯于从release页面去获取最新版本
