### ISSUE TITLE
The version of redis server is too low to support this function

### ISSUE THREAD

**Issue by jesley-sun** [caoxinyu/RedisClient#89]
Redis_Server Version:5.0.5
Redis Client Version:redisclient-win32.x86_64.2.0.jar
连接时报异常：The version of redis server is too low to support this function

**Comment by Creky** [comment]
You can use my temp fixed version: [https://github.com/Creky/RedisClient/tree/windows/release](https://github.com/Creky/RedisClient/tree/windows/release) , only modified version notice.

**Comment by Creky** [comment]
> Redis_Server Version:5.0.5
> Redis Client Version:redisclient-win32.x86_64.2.0.jar
> 连接时报异常：The version of redis server is too low to support this function

You can use my temp fixed version: [https://github.com/Creky/RedisClient/tree/windows/release](https://github.com/Creky/RedisClient/tree/windows/release) , only modified version notice.

**Comment by creky** [comment]
> Redis_Server Version:5.0.5
> Redis Client Version:redisclient-win32.x86_64.2.0.jar
> 连接时报异常：The version of redis server is too low to support this function

You can use my temp fixed version: https://github.com/Creky/RedisClient/tree/windows/release , only modified version notice. Only for win x64 platform. Other platform please clone my code and compile with you platform profile.
