### ISSUE TITLE
Linux 下怎么整

### ISSUE THREAD

**Issue by peidw** [caoxinyu/RedisClient#91]
Linux 下怎么整  ？

**Comment by journeytot-HR** [comment]
这个是windows客户端工具


| |
journeytot
|
|
邮箱：journeytot@126.com
|

Signature is customized by Netease Mail Master

在2019年06月07日 13:20，peidw 写道：

Linux 下怎么整 ？

**Comment by caoxinyu** [comment]
如果你对java比较熟，直接执行jar包就可以。
